### ISSUE TITLE
Создать аккаунт на vscale.io

### ISSUE THREAD

**Issue by djbelyak** [ksst-search/Search#9]

**Comment by djbelyak** [comment]
Это нужно сделать для #10

**Comment by MuxaJlbl4** [comment]
Создал аккаунт и нашёл промо код, сейчас на нём 200 рублей, этого должно хватить на месяц самой простой конфигурации

**Comment by djbelyak** [comment]
Для развертывания MongoDB нужно как минимум 3 машины. Когда баланс будет меньше 50 руб - маякни мне
